# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "文档"
  url = "/docs"
  weight = 20

[[main]]
  name = "Doxygen 文档"
  url = "/docs/doxygen/corlib/html/"
  weight = 20

[[main]]
  name = "版本发布"
  url = "#releases"
  weight = 30

[[main]]
  name = "社区"
  url = "#community"
  weight = 40

[[main]]
  name = "联系"
  url = "#contact"
  weight = 60
